### ISSUE TITLE
Install Docker + Docker Compose support as dependencies

### ISSUE THREAD

**Issue by typemismatch** [awslabs/aws-greengrass-provisioner#322]
We need new dependencies installed;

Docker Engine + Compose support.

**Comment by timmattison** [comment]
Not a problem. For the --script option I just need to know what the dependencies are called in the mainline yum and apt repos. If the mainline ones are not up to date we'll have to figure out what steps are required to add the necessary repos to get dependencies that work for you. I had an issue with Docker in the past because of this, not sure if it's still an issue.

**Comment by typemismatch** [comment]
For Ubuntu - this works;

sudo apt install docker.io

**Comment by timmattison** [comment]
And these packages are up to date? Last time I tried to use them they were out of date and I needed to add another repository I think.

**Comment by timmattison** [comment]
Looking into Amazon Linux 2...

**Comment by timmattison** [comment]
Looks like Docker dependencies are slightly different in the main repos between Ubuntu and AL2. AL2 has 18.09.9-ce, Ubuntu has 18.09.7.

On MacOS installing with Docker desktop gives me 19.03.5.

Looks like I'll need to do some manual steps to get it running with the right version. I just don't want people to test locally with 19 and then have it fail with 18 for whatever reason.

**Comment by typemismatch** [comment]
Yes on AL2 nothing works - I have the install bits for AL2, will find and post.

**Comment by timmattison** [comment]
Getting there. Just sorting out some issues with other dependencies being broken on first install at the moment...

**Comment by timmattison** [comment]
pip3 is killing me. The fact that it moves around when you upgrade it is definitely a headache.
